[package]
name = "bbbul"
description = "Bumpalo-based bitpacked unsigned-integer list"
version = "0.1.0"
edition = "2021"

[dependencies]
bitpacking = "0.9.2"
bumpalo = "3.16.0"

[dev-dependencies]
rand = "0.8.5"
